var objResources = {
IDS_VS_read:"Message marked as read. The alert will no longer be displayed in the notifications channel.",
IDS_COURSESEARCH_COURSERESULTUX_ALERT1:"Not yet implemented.",
IDS_COURSESEARCH_COURSERESULTUX_ALERT2:"Not yet implemented.",
IDS_PROGRAMADMIN_COURSETEMPLATES_ALERT1:"Row with Index: ",
IDS_PROGRAMADMIN_COURSETEMPLATES_ALERT2:"  was created",
SkillSTDSpaceErrMsg:"The skill/standard code cannot contain spaces.",
IDS_PROGRAMADMIN_ENROLLMENTCOURSES_MSGBRD:"To view the templates after copying is complete, wait a few minutes than return to or refresh this page.",
IDS_PROGRAMADMIN_ENROLLMENTCOURSES_LBLSEARCHIT1:"Find Section",
IDS_PROGRAMADMIN_ENROLLMENTCOURSES_LBLSEARCHIT2:"Find Section",
IDS_PROGRAMADMIN_ENROLLMENTCOURSES_TEMP:"Templates",
IDS_PROGRAMADMIN_COURSETEMPLATES_ACTIVE:"Active",
IDS_PROGRAMADMIN_COURSETEMPLATES_INACTIVE:"Inactive",
IDS_ASSESSMENTTOOL_RUBRICS_EDIT:"edit",
IDS_ASSESSMENTTOOL_RUBRICS_RBCDEL:"Rubric schema deleted successfully from the activity.",
IDS_ASSESSMENTTOOL_RUBRICS_CRITERIADEL:"Criterion deleted successfully from the schema.",
IDS_ASSESSMENTTOOL_RUBRICS_QUESTIONMAP:"Questions mapped successfully to the criterion.",
IDS_ASSESSMENTTOOL_RUBRICS_CRITERIADON:"Criterion cell authoring saved successfully.",
IDS_ASSESSMENTTOOL_RUBRICS_CRITERIAADD:"Criterion added successfully to the schema.",
IDS_ASSESSMENTTOOL_RUBRICS_CRITERIAEDIT:"Criterion edited successfully.",
IDS_ASSESSMENTTOOL_RUBRICS_SLESCH:"Please select a schema from the list.",
IDS_ASSESSMENTTOOL_RUBRICS_RBCSCHADDED:"Rubric schema added successfully to the assessment.",
IDS_ASSESSMENTTOOL_RANDOM_CONF_MSG1:"Grade deleted successfully.",
IDS_COURSEANNOUNCEMENT_ALERT1:"Please select a template that has sections",
IDS_COURSEANNOUNCEMENT_MS1:"Multiple Selected (",
IDS_COURSEANNOUNCEMENT_MS2:"Multiple Selected (",
IDS_COURSEANNOUNCEMENT_MS3:"Multiple Selected (",
IDS_QUESTIONSET_QUESTIONSET_NO_SCENARIOS:"There are no scenarios.",
IDS_MEDIALIBRARY_MEDIALIBRARYUX_MEDIA_TYPES:"Media Types:",
IDS_MEDIALIBRARY_MEDIALIBRARYUX_SHOW_ALL:"Show all",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_PROCESSED:"Processed ",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_OF:" of ",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_QUESTION_FILES:" question files",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_ERROR:"Error",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_FIREWALL_WINXP:"The firewall can only be opened on WinXP SP2 machines.",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_FIREWALL_OFF:"The Windows firewall is off!",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_FIREWALL_PRIVILEGES:"You must  have administrative privileges to access the firewall.",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_FIREWALL_PRIVILEGES1:"You must have administrative privileges to add TAIT 3 to the firewall.",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_FIREWALL_PORT:"The required port could not be opened. Verify your administrative privileges and try again.",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_FIREWALL_UNKNOWNERROR:"OpenFirewall() - The firewall could not be successfully opened. Unknown error type ",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_CLICK:"Click",
IDS_SIMINTEGRATION_LAUNCHPLAYER_FIREWALL_WINXP:"The firewall can only be opened on WinXP SP2 machines!",
IDS_SIMINTEGRATION_LAUNCHPLAYER_FIREWALL_OFF:"The Windows firewall is off!",
IDS_SIMINTEGRATION_LAUNCHPLAYER_FIREWALL_PRIVILEGES:"You must  have administrative privileges to access the firewall.",
IDS_SIMINTEGRATION_LAUNCHPLAYER_FIREWALL_PRIVILEGES1:"You must have administrative privileges to add TAIT 3 to the firewall.",
IDS_SIMINTEGRATION_LAUNCHPLAYER_FIREWALL_PORT:"The required port could not be opened. Verify your administrative privileges and try again.",
IDS_SIMINTEGRATION_LAUNCHPLAYER_FIREWALL_UNKNOWNERROR:"OpenFirewall() - The firewall could not be successfully opened. Unknown error type ",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_ERROR:"Error",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_FIREWALL_WINXP:"The firewall can only be opened on WinXP SP2 machines.",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_FIREWALL_OFF:"The Windows firewall is off!",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_FIREWALL_PRIVILEGES:"You must  have administrative privileges to access the firewall.",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_FIREWALL_PRIVILEGES1:"You must have administrative privileges to add TAIT 3 to the firewall.",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_FIREWALL_PORT:"The required port could not be opened. Verify your administrative privileges and try again.",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_FIREWALL_UNKNOWNERROR:"OpenFirewall() - The firewall could not be successfully opened. Unknown error type ",
IDS_SIMINTEGRATION_COMPLETESIMDLLDOWNLOAD_SELECT_FOLDER:"Select the Folder",
IDS_COURSESETTINGS_BEASSESSMENTS_INNERHTML1:"Unavailable",
IDS_COURSESETTINGS_BEASSESSMENTS_INNERHTML2:"Available",
IDS_COURSESETTINGS_DEFAULTPREFE_ATTEMPTS:"Invalid number of attempts entered for Show feedback attempts.",
IDS_COURSESETTINGS_DEFAULTPREFE_ATTEMPTS1:"The attempt at which you want to \"Display Need Help\" is invalid.",
IDS_COURSESETTINGS_DEFAULTPREFE_ALERT:"You must save the default Preferences in order to edit the Help text.",
IDS_COURSESETTINGS_DEFAULTPREFE_ALT1:"More information",
IDS_COURSESETTINGS_DEFAULTPREFE_ALT2:"More information",
IDS_COURSESETTINGS_DEFAULTPREFE_INNERTEXT1:"To customize this Help text, click Edit.",
IDS_COURSESETTINGS_DEFAULTPREFE_INNERTEXT2:"There is no Help text for this option.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM1:"Default font color for page title is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM2:"Default font color for breadcrumb trail is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM3:"Default background color for main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM4:"Default font color for main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM5:"Default active background color for main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM6:"Default active font color for main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM7:"Default hover background color for main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM8:"Default hover font color for main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM9:"Default background color for dropdown menu of main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM10:"Default font color for dropdown menu of main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM11:"Default hover background color for dropdown menu of main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM12:"Default hover font color for dropdown menu of main navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM13:"Default background color for sub-navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM14:"Default font color for sub-navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM15:"Default active font color for sub-navigation is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM16:"Default background color for Course Materials and Calendar is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM17:"Default font color for Course Materials and Calendar is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM18:"Default background color for learning objectives is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM19:"Default font color for learning objectives is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM20:"Default background color for MyTest is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM21:"Default font color for MyTest is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM22:"Default background color for all other toolbars is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM23:"Default font color for all other toolbars is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM24:"Default toolbar background color for Today\'s View is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM25:"Default toolbar font color for Today\'s View is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM26:"Default section label background color for Today\'s View is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM27:"Default section label font color for Today\'s View is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM28:"Default left navigation background color for Today\'s View is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM29:"Default Left navigation font color for Today\'s View is applied",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM30:"Default active background color for Today\'s View is applied.",
IDS_COURSESETTINGS_CUSTOMIZATIONSPRE_CONFIRM31:"Default active font color for Today\'s View is applied.",
IDS_COURSESETTINGS_GENERALPRE_INNERHTML:"You must enter a valid time.",
IDS_COURSESETTINGS_GENERALPRE_INNERHTML1:"You must enter a valid time.",
IDS_COURSESETTINGS_GENERALPRE_CONFIRM:"Due time updated successfully.",
IDS_COURSESETTINGS_GENERALPRE_UNAVAILABLE:"Unavailable",
IDS_COURSESETTINGS_GENERALPRE_UNAVAILABLE1:"Unavailable",
IDS_COURSESETTINGS_GENERALPRE_UNAVAILABLE3:"Unavailable",
IDS_COURSESETTINGS_GENERALPRE_CONFIRM1:"Selected shared library courses are already added to the course.",
IDS_TS_EXCEED_ERR:"There are already the maximum 10 lesson plan views. To create a new one you must delete an existing one.",
IDS_LL_VALIDATE_CUTOFF:"At least one Learner level must have a Cut-off score value of 0.",
IDS_COURSESETTINGS_MYTESTPRE_INNERHTML:"The file you selected for the upgrade image is not a supported image type. Please try again.",
IDS_COURSESETTINGS_PERMISSIONPRE_CONFIRM:"Preferences updated successfully.",
IDS_COURSESETTINGS_PERMISSIONPRE_ALERT:"Preferences not updated",
IDS_COURSESETTINGS_PREFERENCESMAIN_INNETTEXT:"To customize this Help text, click Edit.",
IDS_COURSESETTINGS_PREFERENCESMAIN_INNETTEXT1:"There is no Help text for this option.",
IDS_COURSESETTINGS_PREFERENCESMAIN_ALT:"More information",
IDS_COURSESETTINGS_PREFERENCESMAIN_ALT1:"More information",
IDS_DISCUSSION_DISCUSSIONMAIN_INNERTEXT:"Collapse",
IDS_DISCUSSION_DISCUSSIONMAIN_INNERTEXT1:"Expand",
IDS_ASSESSMENTTOOL_RANDOM_CONF_MSG1:"Grade deleted successfully.",
IDS_ASSESSMENTTOOL_RANDOM_CONF_MSG2:"Grade deleted successfully.",
IDS_ASSESSMENTTOOL_ADAPTIVETREE_ADDQUESTION:"Click Add Questions to begin",
IDS_ASSESSMENTTOOL_CONFIGURED_ALERT1:"Enter the total number of questions in the text box",
IDS_ASSESSMENTTOOL_CONFIGURED_DIRECTION1:"Direction",
IDS_ASSESSMENTTOOL_CONFIGURED_DIRECTION2:"Direction",
IDS_ASSESSMENTTOOL_ASSIGNMENTCONTENT_MSG1:"You have completed the assignment. Click Finish to submit your work for grading. To return to the assignment, click Cancel.",
IDS_ASSESSMENTTOOL_ASSIGNMENTCONTENT_NOHINTS:"There are no more hints.",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_NOHINTS:"There are no more hints.",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_NOLIMIT:"No limit",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_NOLIMIT:"No limit",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_TIME:"Time Remaining:",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_OOPS:"Sorry,",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_TIMEUP:" you have reached the time limit.",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_ILLEGALACCESS:"Either you are not authorized to view this page or the method you used to access this page is not supported.",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_RETURN:"\"Missing XML File Path\"",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_ERROR1:"Error: in Loading -> ",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_ERROR2:"Error: in Object Creation -> ",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_MSG1:"You may select only",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_OPTION1:"options",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_MSG2:"You may select only",
IDS_ASSESSMENTTOOL_COMMANNAVIGATION_OPTION2:"options",
IDS_ASSESSMENTTOOL_FEEDBACK_RETURN:"Missing XML File Path",
IDS_ASSESSMENTTOOL_FEEDBACK_ERROR1:"Error: in Loading -> ",
IDS_ASSESSMENTTOOL_FEEDBACK_ERROR2:"Error: in Object Creation -> ",
IDS_ASSESSMENTTOOL_NAVIGATION_QUESCOUNT1:"Page : ",
IDS_ASSESSMENTTOOL_NAVIGATION_QUESCOUNT2:" out of ",
IDS_ASSESSMENTTOOL_NAVIGATION_QUESCOUNT3:"Item : ",
IDS_ASSESSMENTTOOL_NAVIGATION_QUESCOUNT4:" out of ",
IDS_ASSESSMENTTOOL_NAVIGATION_QUESCOUNT5:"Question : ",
IDS_ASSESSMENTTOOL_NAVIGATION_QUESCOUNT6:" out of  ",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP1:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP2:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP5:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP6:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP7:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_ANSWER:"Correct Answer:",
IDS_ASSESSMENTTOOL_NAVIGATION_FEEDBACK:"Feedback:",
IDS_ASSESSMENTTOOL_NAVIGATION_ANSWER1:" Correct Answer:",
IDS_ASSESSMENTTOOL_NAVIGATION_FEEDBACK1:"Feedback:",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP3:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP4:"Finish",
IDS_ASSESSMENTTOOL_NAVIGATION_TOOLTIP8:"Submit & Get Feedback",
IDS_ASSESSMENTTOOL_NAVIGATION_NQ:"Next Question",
IDS_ASSESSMENTTOOL_NAVIGATION_NQ1:"Next Question",
IDS_ASSESSMENTTOOL_NAVIGATION_NP:"Next Page",
IDS_ASSESSMENTTOOL_NAVIGATION_NP1:"Next Page",
IDS_ASSESSMENTTOOL_NAVIGATION_SCO:"SCO Review",
IDS_QUESTIONLIBRARY_HOTSPOTMULTIPLERESPONSE_ADD_QUESTION:"Add Question",
IDS_QUESTIONLIBRARY_HOTSPOTMULTIPLERESPONSE_HEIGHT:"Height must be between 20 and 500.",
IDS_QUESTIONLIBRARY_HOTSPOTMULTIPLERESPONSE_WIDTH:"Width must be between 200 and 600.",
IDS_QUESTIONLIBRARY_MULTIPLECHOICEDYNAMIC_EXPRESSION:"Unable to preview. Expression may be incorrect.",
IDS_QUESTIONLIBRARY_MULTIPLECHOICEDYNAMIC_EXPRESSION1:"Unable to preview. Expression may be incorrect.",
IDS_QUESTIONLIBRARY_MULTIPLECHOICEDYNAMIC_EXPRESSION2:"Unable to preview. Expression may be incorrect.",
IDS_QUESTIONLIBRARY_MULTIPLERESPONSEDYNAMIC_EXPRESSION:"Unable to preview. Expression may be incorrect.",
IDS_QUESTIONLIBRARY_MULTIPLERESPONSEDYNAMIC_EXPRESSION1:"Unable to preview. Expression may be incorrect.",
IDS_QUESTIONLIBRARY_MULTIPLERESPONSEDYNAMIC_EXPRESSION2:"Unable to preview. Expression may be incorrect.",
IDS_QUESTIONLIBRARY_SLIDER_JAVA:"Java not supported.",
IDS_QUESTIONLIBRARY_SLIDER_JAVA1:"Java not supported.",
IDS_QUESTIONLIBRARY_EASSAY_MAXIMUM:"Maximum record time is 5 minutes.",
IDS_WEB_ASSESSMENTSCHEDULING_STARTDATE:"Phase 1 start date must be greater than the current date.",
IDS_WEB_ASSESSMENTSCHEDULING_STARTDATE1:"Phase 1 start date must be greater than the current date.",
IDS_WEB_ASSESSMENTSCHEDULING_STARTDATE2:"Phase 1 start date must be greater than the current date.",
IDS_WEB_ASSESSMENTSCHEDULING_STARTDATE3:"Start date must be less than the Phase 1 start date.",
IDS_WEB_ASSESSMENTSCHEDULING_STARTDATE4:"Start date must be less than the Phase 1 start date.",
IDS_WEB_ASSESSMENTSCHEDULING_STARTDATE5:"Start date must be less than the Phase 1 start date.",
IDS_WEB_ASSESSMENTSCHEDULING_ENDDATE:"End date must be greater than the Phase 3 start date.",
IDS_WEB_ASSESSMENTSCHEDULING_ENDDATE1:"End date must be greater than the Phase 3 start date.",
IDS_WEB_ASSESSMENTSCHEDULING_ENDDATE2:"End date must be greater than the Phase 3 start date.",
IDS_WEB_ASSESSMENTSCHEDULING_DUEDATE:"Due date must be less than Phase 1 end date.",
IDS_WEB_ASSESSMENTSCHEDULING_DUEDATE1:"Due date must be less than Phase 1 end date.",
IDS_WEB_ASSESSMENTSCHEDULING_DUEDATE2:"Due date must be less than Phase 1 end date.",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_QUESTION:"Edit Question",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_QUESTION:"Add Question",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_ANSWER:"Edit Answer",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_SOLUTION:"Edit Solution",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_TEXT:"Edit Text Settings",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_ANSWER:"Add Answer",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_SOLUTION:"Add Solution",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_TEXT:"Add Text Settings",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_CHOICE:"Edit Choice",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_SCORE:"Edit Score and Feedback",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_SCORE:"Add Score and Feedback",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_CHOICE:"Add Choice",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_GRAPHIC:"Edit Graphic",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_TEXT1:"Edit Text",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_GRAPHIC:"Add Graphic",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_TEXT1:"Add Text",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_OUTCOME:"Edit Outcome",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_OUTCOME:"Add Outcome",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_HOTSPOT:"Edit Hotspot",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_HOTSPOT:"Add Hotspot",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_EDIT_POINTS:"Edit Points",
IDS_QUESTIONLIBRARY_QUESTIONLAYOUT_ADD_POINTS:"Add Points",
IDS_COURSESETTINGS_GRADINGPRE_CONFIRM1:"Case sensitive preference updated successfully.",
IDS_COURSESETTINGS_GRADINGPRE_CONFIRM2:"Case sensitive preference not updated.",
IDS_COURSESETTINGS_GRADINGPRE_CONFIRM3:"Ignore extra spaces preference updated successfully.",
IDS_COURSESETTINGS_GRADINGPRE_ALERT1:"Ignore extra spaces preference not updated",
IDS_COURSESETTINGS_GRADINGPRE_CONFIRM4:"Ignore punctuation preference updated successfully.",
IDS_COURSESETTINGS_GRADINGPRE_ALERT2:"Ignore punctuation preference not updated",
IDS_COURSESETTINGS_GRADINGPRE_CONFIRM5:"Accent preference updated successfully.",
IDS_COURSESETTINGS_GRADINGPRE_ALERT3:"Accents preference not updated",
IDS_COURSESETTINGS_GRADINGPRE_TXTWHOMEVAL:"Course Average",
IDS_COURSESETTINGS_GRADINGPRE_TXTTOPVAL:"Folder Average",
IDS_COURSESETTINGS_GRADINGPRE_ALERT4:"Please select at least one activity.",
IDS_PREF_GRADING_VALID_FOLDER_LEVEL_SCORE:"Threshold score must be between 1 to 100.",
IDS_WEB_FEEDBACK_PLEASE_WAIT:"Page is loading. Please wait…",
IDS_WEB_FEEDBACK_SHOW:"Show Student Actions",
IDS_WEB_FEEDBACK_HIDE:"Hide Student Actions",
IDS_WEB_FEEDBACK_SHOW_INFO:"Show Info",
IDS_WEB_FEEDBACK_HIDE_INFO:"Hide Info",
IDS_WEB_FEEDBACK_HIDE_INFO1:"Hide Info",
IDS_WEB_FEEDBACK_SHOW_INFO1:"Show Info",
IDS_WEB_FEEDBACK_HIDE_INFO2:"Hide Info",
IDS_WEB_DRTUX_CANCEL:"Cancel",
IDS_WEB_DRTUX_STUDY:"You may only access this item from specific computers. Contact your instructor for details.",
IDS_WEB_DRTUX_FINAL:"You can only try this activity once. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_DRTUX_FINAL1:"This is the last time you can complete this activity. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_DRTUX_FINAL2:"This is the last time you can complete this activity. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_DRTUX_FINAL3:"You can only try this activity once. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_DRTUX_FINAL4:"You can only try this activity once. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_DRTUX_FINAL5:"This is the last time you can complete this activity. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_DRTUX_VIEW:"View progress",
IDS_WEB_DRTUX_HIDE:"Hide progress",
IDS_WEB_DRTUX_VIEW1:"View progress",
IDS_WEB_DRTUX_HIDE1:"Hide progress",
IDS_QUESTIONLIBRARY_DRAGANDDROPTEXT_HEIGHT:"Height must be between 200 and 500.",
IDS_QUESTIONLIBRARY_DRAGANDDROPTEXT_WIDTH:"Width must be between 200 and 600.",
IDS_MYPREFERENCE_MYACCOUNTSETTING_ENTER_LNAME:"Please enter last name.",
IDS_WEB_NAVIGATION_PAGE:"Page : ",
IDS_WEB_NAVIGATION_OUT:" out of ",
IDS_WEB_NAVIGATION_QUESTION:"Question : ",
IDS_WEB_NAVIGATION_OUT1:" out of",
IDS_WEB_NAVIGATION_CORRECT:"Correct Answer:",
IDS_WEB_NAVIGATION_FEEDBACK:"Feedback:",
IDS_WEB_NAVIGATION_CORRECT1:"Correct Answer:",
IDS_WEB_NAVIGATION_FEEDBACK1:"Feedback:",
IDS_COURSESEARCH_COURSERESULTUX_ALERT2:"Not yet implemented.",
IDS_COURSESETTINGS_ACTIVITIESPREFERENCES_EDIT:"Edit",
IDS_COURSESETTINGS_ACTIVITIESPREFERENCES_EDIT1:"Edit",
IDS_COURSESETTINGS_ACTIVITIESPREFERENCES_CONFIRM:"Feedback deleted successfully.",
IDS_COURSESETTINGS_ACTIVITIESPREFERENCES_CONFIRM1:"Feedback deleted successfully.",
IDS_WEB_GENERALSCRIPT_VALID_DATE:"Enter valid date in DD/MM/YYYY format for ",
IDS_WEB_GENERALSCRIPT_YEAR:"Year cannot be less than or equal to zero in ",
IDS_WEB_GENERALSCRIPT_MONTH:"Month must be between 1 and 12 in ",
IDS_WEB_GENERALSCRIPT_DAY:"Day must be between 1 and 31 in  ",
IDS_WEB_GENERALSCRIPT_MONTH1:"Month ",
IDS_WEB_GENERALSCRIPT_DOESNOT:"does not have 31 days in",
IDS_WEB_GENERALSCRIPT_FEBRUARY:"February in ",
IDS_WEB_GENERALSCRIPT_DEESNOT1:"does not have",
IDS_WEB_GENERALSCRIPT_DAYS:" days in ",
IDS_WEB_GETAPPLETVALUE_PLEASE:"Please enter the numeric value.",
IDS_WEB_GETAPPLETVALUE_PLEASE1:"Please enter the numeric value.",
IDS_ASSESSMENTTOOL_STORERESPONSE_RETURN:"Missing XML file path.",
IDS_ASSESSMENTTOOL_STORERESPONSE_ERROR:"Error: in Loading -> ",
IDS_ASSESSMENTTOOL_STORERESPONSE_ERROR1:"Error: in Object Creation -> ",
IDS_ASSESSMENTTOOL_STORERESPONSE_NOTFIND:"Could not find an installed XML parser",
IDS_ASSESSMENTTOOL_STORERESPONSE_NOTFIND1:"Could not find an installed XML parser",
IDS_ASSESSMENTTOOL_STORERESPONSE_BROWSER:"Your browser does not support XmlHttp objects",
IDS_ASSESSMENTTOOL_STORERESPONSE_BROWSER1:"Your browser does not support XmlHttp objects",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_NOT_IMPLEMENTED:"Not yet implemented.",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_NOT_IMPLEMENTED1:"Not yet implemented.",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_NOT_IMPLEMENTED2:"Not yet implemented.",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_NOT_IMPLEMENTED3:"Not yet implemented.",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_NOT_IMPLEMENTED4:"Not yet implemented.",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_HBC:"HBC",
IDS_LEARNINGOBJECTIVESUX_LEARNINGOBJECTIVESUX_HBC1:"HBC",
IDS_ASSESSMENTTOOL_RUBRICCONTENT_CONFIRM:"Items deleted successfully from criterion.",
IDS_MYPEGASUS_MYPEGASUS_TXTVALUE:"Author, Title or ISBN, Program Name",
IDS_ORGANIZATIONMANAGEMENT_CREATEORGANISATION_SCHOOL:"school",
IDS_ORGANIZATIONMANAGEMENT_CREATEORGANISATION_SCHOOL1:"school",
IDS_DISCUSSION_REPLYTODISCUSSION_ALERT1:"Message posted successfully.",
IDS_MYPREFERENCE_MYACCOUNTSETTING_ENTER_FNAME:"Please enter first name.",
IDS_TODAYSVIEW_TODAYSVIEWUX_PLEASE_WAIT:"Please wait while we accept all of the submissions for your course.",
IDS_WEB_BASE_PEGASUS_HOME:"Pegasus Home",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML4:"Show Question Details",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML6:"Show Question Details",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML8:"Collapsing...",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML5:"Hide Question Details",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML9:"To add questions to your test, drag a question from the testbank and drop it here or use the check box to select questions and click Add.",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML1:"Filter Testbank (On)",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML7:"Expanding...",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML3:"Hide Question Details",
IDS_PEGASUSTEST_PAPERTESTUX_INNERHTML2:"Filter Testbank",
IDS_COURSECATALOG_FRMCATALOGSEARCHRESULTS_TITLE:"Title",
IDS_COURSECATALOG_FRMCOURSEUPGRADE_ALREADY_CREATED:"Course already created.",
IDS_MYPREFERENCE_MYACCOUNTSETTING_ENTER_LNAME:"Please enter last name.",
IDS_WEB_GRADEBOOKUX_NEW_SCHEMA:"Add New Schema",
IDS_WEB_GRADEBOOKUX_UPDATE_SCHEMA:"Update Schema",
IDS_WEB_GRADEBOOKUX_GRADE:"Grade weight cannot be zero percent.",
IDS_WEB_GRADEBOOKUX_ENTER:"Enter Grade Weight",
IDS_WEB_GRADEBOOKUX_SOME:"Some activities are already added.",
IDS_WEB_RECORD_APPLET:"(The applet will appear only on web pages served by a web server, not on web pages accessed through the file system.)",
IDS_WEB_RECORD_WARNING:"Warning: this platform is not supported.",
IDS_WEB_RECORD_SETUP:"Setup Wizard",
IDS_WEB_RECORD_REFERESH:"Refresh",
IDS_WEB_RECORD_HORIZON:"Horizon Wimba Tool loading...",
IDS_WEB_RECORD_JAVA:"Either Java is not installed or you have an older version that is not supported. Please run the",
IDS_WEB_RECORD_WIZARD:"Setup Wizard",
IDS_WEB_RECORD_AND:"and install Java when prompted.",
IDS_WEB_RECORD_MESSAGE:"Message does not exist.\\(You need to be online\\to play this message)",
IDS_WEB_RECORD_SHOULD:"Applet is available, but the server for the voice tools is currently unavailable.",
ID_ManageAddLibrary:"The selected course materials were successfully added to your course.",
FW_SC_Name_ErrMsg:"Framework name cannot contain special characters.",
FW_SC_Code_ErrMsg:"Framework/Skill Standard code cannot contain special characters.",
FW_SC_Space_ErrMsg:"The Framework code cannot contain spaces.",
FrameworkName_ErrMsg:"Framework name must be between 1 and 100 characters.",
FrameworkCode_ErrMsg:"Framework code must be between 1 and 50 characters.",
FrameworktDesc_ErrMsg:"Description cannot exceed 400 characters.",
FW_SC_Name_ErrMsg:"Framework name cannot contain special characters.",
FW_SC_Code_ErrMsg:"Framework/Skill Standard code cannot contain special characters.",
FW_SC_Space_ErrMsg:"The Framework code cannot contain spaces.",
FrameworktThreshold_ErrMsg:"Threshold score must be between 0 and 100.",
8047:"Please select the file",
6101:"You can only select a .csv file.",
IDS_WEB_RECORDAUDIO_AND:"and install Java when prompted.",
IDS_WEB_RECORDAUDIO_APPLET:"(The applet will appear only on web pages served by a web server, not on web pages accessed through the file system)",
IDS_WEB_RECORDAUDIO_PLEASE:"Please run the",
IDS_WEB_RECORDAUDIO_REFERESH:"Refresh",
IDS_WEB_RECORDAUDIO_SETUP:"Setup Wizard",
IDS_WEB_RECORDAUDIO_WARNING:"Warning: this platform is not supported.",
IDS_WEB_RECORDAUDIO_WIZARD:"Setup Wizard",
IDS_WEB_RECORDAUDIO_HORIZON:"Horizon Wimba Tool loading...",
IDS_WEB_RECORDAUDIO_JAVA1:"Either Java is not installed or you have an older version that is not supported. Please run the",
IDS_WEB_RECORDAUDIO_WIZARD1:"Setup Wizard",
IDS_WEB_RECORDAUDIO_AND1:"and install Java when prompted.",
IDS_WEB_RECORDAUDIO_PLEASE1:"Please run the Setup Wizard and install Java when prompted.",
IDS_WEB_RECORDAUDIO_JAVA2:"Either Java is not installed or you have an older version that is not supported.",
IDS_WEB_RECORDAUDIO_MESSAGE:"Message does not exist.\\(You need to be online\\to play this message)",
IDS_WEB_RECORDAUDIO_APPLET1:"Applet is available, but the server for the voice tools is currently unavailable.",
IDS_WEB_REPORTSUX_PLEASE:"You must select at least one section.",
IDS_WEB_REPORTSUX_PLEASE1:"You must select at least one section.",
IDS_WEB_REPORTSUX_SHOW:"(Show all)",
IDS_WEB_REPORTSUX_COLLAPSE:"Collapse",
IDS_WEB_REPORTSUX_SHOW1:"Show all",
IDS_WEB_REPORTSUX_COLLAPSE1:"Collapse",
IDS_WEB_REPORTSUX_HIDE:"Hide Enrollment",
IDS_WEB_REPORTSUX_SHOW2:"Show",
IDS_WEB_COURSEPREVIEWMAINUX_ONLY:"You can only try this activity once. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_COURSEPREVIEWMAINUX_FINAL:"This is the last time you can complete this activity. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_WEB_COURSEPREVIEWMAINUX_STUDY:"The study guide information must be 2000 characters or less.",
IDS_SKILLSTANDARDFRAMEWORK_FRAMEWORKMANAGEMENT_CODE:"Code",
IDS_SKILLSTANDARDFRAMEWORK_FRAMEWORKMANAGEMENT_ALIGNED:"Aligned Skills/Standards",
IDS_SKILLSTANDARDFRAMEWORK_FRAMEWORKMANAGEMENT_ALIGNED1:"Aligned Skills/Standards",
IDS_WEB_FRMCONTENTBROWSER_MAIN_LOADING:"Loading Windows Media Player components...",
IDS_WEB_LOGIN_YOUR_SESSION:"Your session has timed out. For security reasons, online sessions are closed after inactivity. To continue your session, please enter your username and password and click the Sign in button.",
IDS_SIMINTEGRATION_SIMDLLDOWNLOAD_CLICK:"Click",
IDS_LIC_UNAVAILABILITY:"You are not able to access the class you selected at this time, as all licensed seats are in use. Please contact your instructor or administrator for assistance.",
IDS_LIC_DATE_VALIDATION_MSG:"You do not have access to the item you have selected; please contact your instructor or administrator for assistance.",
VS_ShowUnSubAtt:"Show unsubmitted activities",
VS_HideUnSubAtt:"Hide unsubmitted activities",
IDS_INCOMPLETE:"Incomplete",
IDS_ASSESSMENTTOOL_FRMVIEWSTUDENTSUBMISSION_Complete:"Complete",
IDS_MYACC_CUSTOM_FORMATS:"Please select all number and date formats for Custom Locale.",
IDS_COURSESETTINGS_STUDYPLANPREFERENCES_STANDARDFRAMEWORK:"Select Standard Framework",
IDS_COURSESETTINGS_STUDYPLANPREFERENCES_SKILLFRAMEWORK:"Select Skill Framework",
CAT_MyCourse_IsPrepared:"Course is being prepared and will be available soon.",
CAT_MyFolder_IsPrepared:"Folder is being prepared and will be available soon.",
IDS_COURSESETTINGS_MODULETYPEPREFERENCES_AddEbook:"Add eText Link",
IDS_COURSESETTINGS_MODULETYPEPREFERENCES_Title:"Title",
IDS_COURSESETTINGS_MODULETYPEPREFERENCES_DefaultIcon:"Default Icon",
IDS_COURSESETTINGS_MODULETYPEPREFERENCES_ThereAre:"There are no eTexts found in the Course",
IDS_GRADEBOOK_GBINSTRUCTOR_CreateCalculatedColumn:"Create Calculated Column",
IDS_GRADEBOOK_GBINSTRUCTOR_CreateNumericColumn:"Create Numeric Column",
IDS_GRADEBOOK_GBINSTRUCTOR_CreateSelectionListColumn:"Create Selection List Column",
IDS_GRADEBOOK_GBINSTRUCTOR_CreateTextColumn:"Create Free Text Column",
IDS_MYTEST_FILTERBY:"Filter By",
IDS_PEGASUSTEST_PAPERTESTUX_TestBankandTest:"Testbank and Test",
IDS_PEGASUSTEST_PAPERTESTUX_TestBankOnly:"Testbank Only",
IDS_PEGASUSTEST_PAPERTESTUX_TestOnly:"Test Only",
IDS_WEB_DRTUX_SAVE:"Save",
IDS_PREFTHEME_SUCCESSMSG1:"Module Theme created successfully.",
IDS_PREFTHEME_SUCCESSMSG2:"Module Theme updated successfully.",
IDS_PREF_MODULETYPE_SUCCESSMSG:"Module Types created successfully.",
IDS_PREF_MODULETYPE_UPDATEMSG:"Module Type updated successfully",
IDS_PREFTHEME_VALIDATETAB:"You must specify at least two tab styles.",
IDS_PROGRAMADMIN_FRMENROLLMENTMAIN_AnchorText:"Add as Instructor",
IDS_PROGRAMADMIN_FRMENROLLMENTMAIN_AnchorText1:"Add as Student",
IDS_GEN_ADDASTA:"Add as TA",
IDS_WEB_FEEDBACK_HIDE_INFO2:"Hide Info",
IDS_WEB_FEEDBACK_HIDE_INFO3:"Hide Info",
IDS_WEB_FEEDBACK_HIDE_STUDENT_ACTION:"Hide Student Actions",
IDS_GEN_NEWSKILLSTANDARD_DESC_ON_EMPTY_MSG:"Description cannot be empty.",
IDS_CHANGE_CONTENT_SOURCE:"Change Source",
FrameworktSpanishDesc_ErrMsg:"Spanish Description cannot exceed 4000 characters.",
ID_VIEW_PROGRESS:"View Progress",
ID_HIDE_PROGRESS:"Hide Progress",
7980:"Setting values updated successfully.",
7981:"Unable to update setting values. Please try again.",
IDS_GEN_TV_COURSEPERFORMANCE:"Course_Performance",
TV_COURSEPERFORMANCE_SPANTEXT:"Course Performance",
IDS_GEN_TV_STUDPERFORMANCE:"Student_Performance",
TV_WM_STUDENTPERFORMACE_TEXT:"Student Performance",
IDS_PREF_CCEBOOK_SUCESSMSG:"eText deleted successfully.",
PREF_CC_EBOOKS:"Your course includes links to this eText. To remove this eText, you must first remove those links.",
IDS_QUESTIONLIBRARY_FRMFILLINTHEBLANKS_Text:"Text",
IDS_QUESTIONLIBRARY_FRMFILLINTHEBLANKS_Blank:"Blank",
IDS_ASSESSMENTTOOL_VWSTUDENTSUBMISSION_LBLEDITASSESSMENTGRADE_COLUMNNAME:"Column Name:",
IDS_DISCUSSION_DISCUSSIONUNTHREADEDUX_PREVIOUS:"Previous",
IDS_DISCUSSION_DISCUSSIONUNTHREADEDUX_NEXT:"Next",
IDS_PAGASUSBASEPAGE_PEGASUSHEADER_Close:"Close",
IDS_COMMON_FRMFOLDERDIALOG_SELECT:"Select",
IDS_ADMIN_FRMITIPAGE_DATE:"Date",
FrameworktDescSkillStandard_ErrMsg:"Description cannot exceed 4000 characters.",
6050:"Next",
6049:"Previous",
6058:"No more hints",
1735:"Time up for question: ",
6021:"Please answer all of the questions.",
6047:"Remove flag",
6048:"Flag question",
6025:"Sorry, you have reached the time limit.",
6024:"The maximum options to select are only ",
6026:"minutes remaining",
6025:"Sorry, you have reached the time limit.",
6035:"Hide summary",
6036:"Hide summary",
6027:"Show summary",
6028:"Show summary of activity results",
4008:"Are you sure you want to unenroll the selected users?",
6018:"The minimum options to select are ",
6019:"A Java Applet question is missing. The question will be marked as unattempted.",
6014:"You must answer all questions before submitting the test or activity.",
6015:"You did not answer all of the questions. <br>Do you want to submit the test for grading?",
6016:"<br>Are you sure you want to submit the activity for evaluation?",
6013:"Please wait while your activity is being graded. This may take some time.",
6057:"Hint		",
IDS_Submission_Successful:"Your submission has been successfully updated.",
IDS_PeerPopup_Proc:"Please wait while your peer activity is being processed.",
IDS_Proceed_Next:"You are out of time for this question.  Click Next to go to the next question.",
IDS_Proceed_Continue:"You are out of time for this question.  Click Continue to go to the next question.",
IDS_Feedback_Restriction:"Feedback must be less than 2000 characters.",
IDS_Enter_Numeric:"Please enter a numeric value.",
IDS_Enter_NonDecimal:"Please enter a non-decimal value.",
IDS_Exceed_MAxScore:"The score cannot be greater than the maximum score.",
IDS_TimeUP_Question:"You have exceeded the time allowed for the previous questions.",
IDS_AnswerAll:"You must answer all questions before you can submit your work for grading.",
IDS_Not_AnswerAll:"You did not answer all of the questions. To submit your work for grading, click Finish. To complete your work, click Cancel.",
IDS_Recorder_Paused:"There are paused recordings in your assignment that are not saved. To save, click the stop button in the recording tool and then click on Finish: Submit for grading.",
IDS_Recorder_PausedSFL:"There are paused recordings in your assignment that are not saved. To save, click the stop button in the recording tool and then click on Save For Later to save the attempt.",
IDS_Saves_Over:"You have used all of the saves allowed for this activity. Please complete your work and submit the activity for grading.",
IDS_Save_For_Later:"  Are you sure you want to save and close this activity? If you click Save, the activity is not submitted for grading, and you can open it again to complete it.",
IDS_Abrupt_Close:"Your activity is not complete. If you close the activity your work is not recorded in the gradebook. We recommend you click Cancel to complete your work now.",
IDS_Confirm_Peerscholar:"You have completed evaluating the activity. Click Finish to submit your work for grading. Click Cancel to return to the activity.",
IDS_Confirm_Submission:"You have completed the activity. Click Finish to submit your work for grading. Click Cancel to return to the activity.",
IDS_Answer_Questions:"You must answer any questions you  viewed.",
IDS_Submit_Questions:"You must submit the viewed question before you can save.",
IDS_Restrict_Save:"If you try this activity again you will not be able to view the questions you already read. Do you want to continue?",
IDS_Restrict_Popup:"The answer to this question was saved and cannot be viewed or changed.",
DO_ERROR_03:"Your work cannot be submitted due to a technical problem which may be caused by internet connectivity. Please be sure you maintain a stable internet connection while working in your MyLab. If you continue to experience this error, please copy the Support link info and contact Pearson Technical Support at   <a target=\"_blank\" style=\"text-decoration: none;\" href=\"[[]]\"> [[]] </a> <br> <br>For specific steps on how to copy the Support link info please click <a target=\"_blank\" href=\"[[]]\">here</a>.&nbsp;",
IDS_COURSESETTINGS_MODULE_GEN_TAB:"General",
IDS_Rpt_BASI:"BASI",
IDS_Answer_Question:"You must answer the question before you can submit your work for grading.",
IDS_GEN_GBEditFreeTextColumn:"Edit Free Text Column",
IDS_GEN_GBEditNumericColumn:"Edit Numeric Column",
IDS_GEN_GBEditCalculatedColumn:"Edit Calculated Column",
IDS_GEN_GBEditSelectionListColumn:"Edit Selection List Column",
IDS_GEN_GBEditTotalGradesColumn:"Edit Total Grades Column",
IDS_GEN_GBEditImportGradesColumn:"Edit Import Grades Column",
ID_POP_REMOVE:"Remove",
IDS_HTMLEditor_Subscript:"Subscript",
Hide_Submission:"Hide Submissions List",
IDS_ADD_LIBRARY:"Add Library",
ID_POP_HIDE:"Hide",
ID_POP_SHOW:"Show",
IDS_XSL_NOLIMIT:"No limit",
ID_MSG_FileFormat:"Import file must be in xls format.",
9204:"The SMS Module ID cannot be more than 100 characters.",
5134:"Name cannot be more than 100 characters.",
IDS_DEMO_ACCESS_BLANK:"You must enter demo access code value.",
IDS_DEMO_ACCESSCODE:"Access code must be between 5 to 15 characters.",
IDS_CONTAIN_ALPHANUMERIC:"Access code must only contain alphanumeric characters.",
IDS_Select_Subject:"You must select a Subject in order to create a product.",
IDS_Select_Grade:"You must select a Grade in order to create a product.",
IDS_Select_ProductType:"You must select a Product Type in order to create a product.",
IDS_MSG_CpyRgYr:"You must enter Copyright Year in order to create a product.",
IDS_MSG_InvalidFlFrm:"Invalid file format",
IDS_MSG_FlUpl:"A required image must be uploaded in order to proceed.",
IDS_MSG_ENTERPRO:"You must enter Product Name in order to create a product.",
IDS_MSG_ENTERPRONOTES:"You must enter Notes in order to create a product.",
IDS_SELECT_PROGID:"You must select a program in order to create a product.",
IDS_QS_EDIT:"Edit",
IDS_SLC_ADDED_SUCCESS:"Shared library courses successfully added to the current course.",
IDS_SLC_ALREADY_ADDED:"The shared library courses have been added. Some already were added to the course.",
ID_CB_NOCOURSES:"There are no courses.",
IDS_QL_NARRATIVE:"Narrative:",
ID_MSG_LPTITLE:"Please enter lesson plan title",
ID_MSG_ELEMENT_TITLE:"Please enter element title",
ID_MSG_DIGLESSONURL:"Please enter Lesson Link url",
ID_MSG_ADDOBJECTIVE:"Please enter lesson objective",
ID_MSG_DIGLESSONTITLE:"Please enter Lesson Link title",
ID_MSG_RESOURCE_TEXT:"Please enter resource text",
ID_MSG_RESOURCE_TITLE:"Please enter resource title and url",
ID_MSG_RESOURCE_URL:"Please enter resource url",
IDS_PREF_LP_CODE_ERR:"Upload code value must be alphanumeric characters only.",
IDS_PREF_LP_DESC_ERR:"Description exceeds the 300 character limit.",
ID_ITEMS_ALREADY_MSG:"Items have already been added.",
IDS_PREF_COURSEGLOSSARY_UNIQUEIDVALIDATION:"Unique ID is required. Please enter a Unique ID.",
IDS_PREF_COURSEGLOSSARY_TERMVALIDATION:"Term is required. Please enter a Term.",
IDS_PREF_COURSEGLOSSARY_UIDEXISTS:"Unique ID already exists. Please enter a different Unique ID.",
IDS_PREF_COURSEGLOSSARY_IMAGEVALIDATION:"The image/animation file you selected is not a supported file type. Please try again.",
IDS_PREF_COURSEGLOSSARY_AUDIOVALIDATION:"Please add only .mp3 file as sound file and try again",
IDS_PREF_COURSEGLOSSARY_CAPTIONVALIDATION:"There is no image/animation loaded for this caption. Please upload an image or animation.",
IDS_PREF_SKILLSTDS_SKILLSTDVALIDATION:"To use Standards and Skills, you must add and select a Skills Framework.",
IDS_PREF_MODULES_ADDGLOSSARY:"Add Glossary",
IDS_PREF_MODULES_EDITGLOSSARY:"Edit Glossary",
IDS_PREF_MODULES_GLOSSARYTITLE:"Glossary title",
IDS_PREF_MODULES_GLOSSARYURL:"Glossary URL",
IDS_PREF_MODULES_GLOSSARYSUCMSG:"Module Glossary created successfully.",
IDS_PREF_MODULES_GLOSSARYEDITMSG:"Module Glossary updated successfully.",
IDS_PREF_GLOSSARY_DELETESUCMSG:"Glossary entries deleted successfully.",
IDS_Glossary:"Glossary",
ID_CT_FILE_SIZE_NOT_EXCEED:"Key not added to the global resources file: Pegasus.resx",
IDS_PREF_GLOSSARY_UPDATEMSG:"Glossary Term details updated successfully.",
IDS_GLOSSARY_AUDIOSUCCESSMSG:"New Audio file uploaded successfully.",
IDS_GLOSSARY_IMAGESUCCESSMSG:"Image uploaded  successfully.",
IDS_GLOSSARY_USERDEFINEDMESSAGE14:"Definition exceeds the 1000 character limit",
IDS_GLOSSARY_USERDEFINEDMESSAGE15:"Invalid File Type.",
IDS_GLOSSARY_USERDEFINEDMESSAGE16:"Unique Identifier field is Empty or Text exceeds the 30 character limit",
IDS_GLOSSARY_USERDEFINEDMESSAGE17:"English Term exceeds the 100 character limit",
IDS_GLOSSARY_USERDEFINEDMESSAGE18:"Translation Term exceeds the 100 character limit",
IDS_GLOSSARY_USERDEFINEDMESSAGE19:"Image Caption length exceeds the 140 character limit",
IDS_GLOSSARY_USERDEFINEDMESSAGE20:"English Term field is mandatory.",
IDS_GLOSSARY_USERDEFINEDMESSAGE21:"Term field is mandatory.",
IDS_GLOSSARY_AUDIODELETED:"Audio removed successfully.",
IDS_GLOSSARY_IMAGEDELETED:"Image removed successfully",
IDS_GLOSSARY_TERMADDED:"Term Added",
IDS_PREF_GLOSSARY_DELMODULE:"A glossary has already been added to the module. Do you still want to delete?",
IDS_PREF_GLOSSARY_DELMODULEGLOSSARY:"Please delete the existing glossary before selecting a different glossary option.",
IDS_PREF_GEFILEUPLOAD:"Please select a .zip file.",
IDS_PREF_GLOSSARY_PASTEDEFMSG:"Definition exceeds the 1000 character limit.",
IDS_PREF_GLOSSARY_PASTEUIDMSG:"Unique ID must be alphanumeric characters only.",
IDS_GLOSSARY_UPDATED:"Glossary changes have been saved.",
920054:"Z",
IDS_LEARNERLEVEL_ERR1:"Enter the Level name and Cut-off percentage",
IDS_LEARNERLEVEL_ERR2:"Enter the Level name and Cut-off percentage for the existing row.",
IDS_CUTOFFSCORE_EXCEED_ERR:"Please enter a cut-off percentage between 0 - 100.",
IDS_LEARNERLEVEL_MINROW_ERR:"When Enable Learner Levels is selected, there must be at least one Learner Level defined.",
IDS_GEN_EDIT:"Edit",
IDS_GEN_DELETE:"Delete",
IDS_PB_NAME_CHGBGCLR:"If you change the background color it is applied to all slides. Do you want to change? Yes/No",
IDS_PB_NAME_CHGTEXT:"Text in the text field will be lost if you switch to this page layout.  Do you want to continue? Yes/No",
IDS_PB_NAME_CHGIMAGE:"Image in text field will be lost if you switch to this page layout.  Do you want to continue? Yes/No",
IDS_PB_NAME_BUILDERLYTCLK:"Click \"EDIT\" to edit this text.",
IDS_PB_NAME_BUILDERLYT:"To add media here, drag and drop from your Tracker.",
IDS_PB_NAME_BUILDERSLIDE:"Please select a layout for this page.",
IDS_PB_ERROR:"Error in Submission",
IDS_GEN_CANCEL:"Cancel",
IDS_GEN_OK:"OK",
IDS_PB_SLIDE_DELETE:"This option is final and cannot be undone.  Would you like to continue? ",
IDS_PB_SLIDE_CONTENTDELETE:"This option is final and cannot be undone.  Would you like to continue? ",
IDS_XSL_QUESTIONNOTATTEMPTED:"Question was not attempted",
IDS_INSTRUCTOR_SUBMIT:"The student already used the current submission attempt.",
IDS_PRODUCT_Invalid_Case:"This product cannot be added to this program due to a conflict of product type.",
IDS_GEN_UPDATE:"Update",
IDS_ORG_REMOVEMSG_HAS_LICENSEPRODUCTS:"This organization cannot be removed because it contains licensed products.",
IDS_ORG_REMOVEMSG_HAS_ACTIVEUSERS:"This organization cannot be removed because it contains active users.",
IDS_ORG_REMOVEMSG_HAS_CHILDORGANISATION:"This organization cannot be removed because it contains other organizations.",
IDS_ORG_REMOVEMSG_HAS_ACTIVECLASSES:"This organization cannot be removed because it contains active classes.",
IDS_ORG_REMOVEMSG_SUCCESS:"Organization was successfully removed.",
IDS_ORG_REMOVEMSG_FAILURE:"This organization was not removed. Please try again later.",
IDS_HPF_MOVE_UP:"Move Up",
IDS_HPF_MOVE_DOWN:"Move Down",
IDS_VIEWED:"Viewed",
IDS_MSG_SELECT_PRODUCT:"Please select the item you want to add.",
IDS_MSG_NO_CONTENT:"You currently do not have any programs. Click the Add Programs button to select the programs you want to use.",
ID_AUDIO_LOADING:"Loading...",
IDS_TSL_CANNOTCLOSE_MSG:"You cannot close the folder when items in the folder are selected.",
IDS_Organization_Library_Added_Successfully:"Organization libraries added successfully.",
IDS_COURSESETTING_AVAILABLE:"Available",
IDS_COURSESETTING_UNAVAILABLE:"Unavailable",
IDS_PREF_LESSONPLAN_CODEVALIDATIONMSG:"The Upload Code must be unique for this course. Please enter another code and save again.",
IDS_PREF_LESSONPLAN_CREATESUCMSG:"Lesson plan view created successfully.",
IDS_PREF_LESSONPLAN_UPDATESUCMSG:"Lesson plan view updated successfully.",
IDS_PREF_LESSONPLAN_DELETESUCMSG:"Lesson plan view deleted successfully.",
IDS_PREF_LESSONPLAN_DELETENONSUCMSG:"This lesson plan view is being used in the course. To remove it you must remove all elements associated with this view.",
IDS_PREF_TEACHINGSTYLE_TITLEVALMSG:"Title is required. Please enter title.",
IDS_PREF_TEACHINGSTYLE_CODEVALMSG:"Upload code is required. Please enter Upload code.",
IDS_PREF_TEACHINGSTYLE_ICONVALMSG:"Please select the file for icon",
ID_LP_DESCRIPTION:"Description",
ID_LP_MATERIALS:"Overview/Materials",
IDS_ALERTMSG_ELEMENT:"Element title cannot be blank",
ID_ALREADY_MSL:"Selected items already exist.",
IDS_PREF_TEACHINGSTYLE_SAVEVALMSG:"At least one lesson plan view is required.",
TV_CUSTOMIZE:"CUSTOMIZE",
ID_MSG_LPINDEXCODE:"Please enter lesson plan index",
ID_MSG_RESOURCETITLE:"Resource text cannot be more than 1000 characters",
ID_MSG_MYNOTES:"My notes text cannot be more than 4000 characters",
ID_MSG_HOMEWORK:"Homework text cannot be more than 4000 characters",
ID_MSG_EDITOR:"Editor text cannot be more than 4000 characters",
5154:"Items deleted successfully.",
5159:"Item deleted successfully.",
5157:"Items copied successfully.",
5158:"Selected items moved successfully.",
9289:"Discussion topic saved successfully.",
9290:"Discussion topic updated successfully.",
5145:"Folder saved successfully.",
5146:"Folder updated successfully.",
5147:"Link saved successfully.",
5148:"Link updated successfully.",
5149:"File saved successfully.",
5150:"File updated successfully.",
5185:"WPS files added successfully.",
5186:"Practice lesson saved successfully.",
5187:"Practice lesson updated successfully.",
EBOOK_LINK_SAVED:"eText link saved successfully.",
EBOOK_LINK_UPDATED:"eText link updated successfully.",
LESSON_PLAN_SAVED:"Lesson Plan saved successfully.",
LESSON_PLAN_UPDATED:"Lesson Plan updated successfully.",
CUSTOM_CONTENT_SUCCEED:"You have successfully added custom content.",
CUSTOM_LESSON_PLAN_CONTENT_SUCCEED:"You have successfully added content to custom lesson plan.",
IDS_PRODUCT_BROWSE_LessonPlan:"Browse Lesson Plans",
IDS_TSL_CANNOTCLOSEMSG:"Key not added to the global resources file: Pegasus.resx",
IDS_LUNCH_TEXT:"Launch eText",
ID_DONT_REMIND:"Don\'t remind me again.",
ID_TSL_CLIPBOARD:"clipboard items. To paste items, click Paste on a destination folder.",
ID_There_are:"There are",
IDS_NOEBOOK:"No eTexts are associated with this content",
IDS_Product_Subscribe_Success_Msg:"Done! Your program/course has been created.",
IDS_Subscription_Failed:"SUBSCRIPTION FAILED",
IDS_PL_success:" saved successfully.",
IDS_PL_Update_success:" updated successfully.",
IDS_CREATING_CONTENT:"Creating",
IDS_CUSTOMIZING_CONTENT:"Customizing",
ID_No_eTexts_exist:"There are no eTexts",
ID_AMPLIFIRE_UPDATE:"Amplifire Link updated successfully.",
IDS_MULUPLOAD_INVALID_MIMETYPE:"Some of the executable file types [ex: .exe, .bat, .vss] you are trying to upload are not uploaded.",
ID_ADMIN_TEMPLATE_DEMOUSER_SELECTCLASS:"Please enter a class name",
ID_ADMIN_TEMPLATE_DEMOUSER_ACCESSCODE:"Select demo access code",
IDS_DEMOREGISTRATION_SELECTSTATE:"Please select a State/Province",
IDS_DEMOREGISTRATION_SELECTSTATEFIRST:"Please select a state first.",
IDS_DEMOREGISTRATION_ENTEREMAIL:"Email required.",
IDS_REG_PASSWORDMAXLIMIT:"Password must be at least 8 characters and maximum 32 characters. It must include a numeric or special character. It should not contain first name, last name or username.",
IDS_DEMO_ACCESSCODE:"Access code must be between 5 to 15 characters.",
IDS_REG_USERNAME:"Username must be between 1 and 120 characters.",
IDS_REG_LASTNAME:"Last name must be between 1 and 50 characters.",
IDS_REG_FIRSTNAME:"First name must be between 1 and 50 characters.",
IDS_DEMO_ZIPCODE_US:"Please enter a Zip code with 5 digits.",
IDS_DEMO_ZIPCODE_Canada:"Please enter a ZIP/Postal code with 5 to 15 characters.",
5135:"Please enter a valid E-mail address.",
IDS_DEMOREGISTRATION_SPECIALCHARACTERS:"Special characters are not allowed.",
IDS_DEMO_USERNAME_EIXSTS:"The username is already taken!",
IDS_DEMO_USERNAME_VALID:"Username is available.",
IDS_DEMO_NAME_VALID:"Name looks great.",
IDS_DEMO_NAME_INVALID:"You must enter your first and last name. Max 50 characters.",
IDS_DEMO_EMAILID_VALID:"We will email you a confirmation.",
IDS_DEMO_PASSWORD_VALID:"Password looks great.",
IDS_DEMO_ACCESS_CODE_VALID:"Demo access code looks great.",
IDS_DEMO_WATERMARK_USERNAME:"First and last name",
IDS_DEMO_WATERMARK_EMAILID:"Any email address acceptable",
IDS_GEN_USRNAME:"Username",
IDS_GEN_PASSWORD:"Password",
187:"Demo Access Code",
IDS_DEMOREGISTRATION_SCHOOLNAME:"School Name",
IDS_FRMDEMOREGISTRATION_VALIDATING:"Validating",
IDS_GEN_DemoZipCode:"Zip/Postal Code",
CMENUITEM_OL_ENTER_CLASS_TEACHER:"Enter",
IDS_COURSESETTINGS_MODULETHEME_IMPORTTEXT:"Browse the Master Course folders to select a theme to import.",
ID_Rpt_SelectAll_2:"Select All",
IDS_LL_NO_OVERLAP:"Cut-off scores cannot overlap",
IDS_LL_NO_DUPLICATE:"Learner levels cannot have duplicate names",
IDS_LL_NAME:"Enter the Level name",
IDS_LL_CUTTOFF:"Enter the cut-off percentage",
IDS_LL_ONE_MUST_ZERO:"Cut-off scores represent the lowest possible percentage score for a given learner level. As such, one level must include zero as its cut-off score. Values of 101 or greater are not accepted.",
IDS_LL_ONE_MUST:"You must enter at least one Learner Level.",
IDS_LL_ONE_DEFAULT:"Learner Levels should contain one Default Level.",
IDS_LL_ONE_MUST_ZERO_CUTTOFF:"One learner level must have zero value for cut-off score.",
IDS_LL_HAVE_REFERENCES:"You currently have content that references learner levels.  You must delete these references in order to add or remove a learner level.",
IDS_DELETE_LL_ALERT:"You are unable to delete Learner Levels at this time as they are in use by Writing Assistant activities.  Please edit the Writing Assistant preferences to use a different Student Workflow before deleting the Learner Levels.",
IDS_DISCUSSION_ADD:"Add",
IDS_File_MSg:"Topic is required to use the subtopic entry.",
IDS_BUTTON_CONTINUE:"Continue",
IDS_ASSESSMENTTOOL_FRMASSIGNMENTTEST_JsTitle:"Finish",
IDS_PREF_MODULETHEMES_DEFAULTDELETEMSG:"You cannot delete the default theme from the course.",
5186:"Practice lesson saved successfully.",
5187:"Practice lesson updated successfully.",
IDS_COURSESETTINGS_MODULES_MODULETYPES:"Module Types",
IDS_COURSESETTINGS_MODULES_TOOLS:"Module Tools",
IDS_FILE_MSG_IDFIELD:"You can only enter alphanumeric characters for the ID",
IDS_PREFTHEME_ERRORMSG:"You must select an image to upload.",
IDS_REG_ROLELOCATIONSELECT:"You must select a role before saving the location you are adding.",
IDS_Abrupt_Close_LastAttempt:"This is the last time you can complete this activity. If you close the activity your work will be submitted and you will not be able to try again. Click Cancel to complete your work now.",
IDS_Abrupt_Close_FirstAttempt:"You can only try this activity once. If you close the activity your work will be submitted and you will not be able to try again. Click Cancel to complete your work now.",
IDS_CALENDARCHANNEL_NOCALENDARSETUPMESSAGE:" Please go to the Planner page to set up your calendar.",
IDS_CAL_SETUPMESSAGE:"Click Pearson Content and then click the Calendar button (at the top left of the product page) to set up your calendar.",
IDS_GEN_CURRENTPWD:"Current password cannot be blank.",
IDS_MYPREFERNCES_NEW_UERNAME:"Current username cannot be blank.",
5099:"Username must be between 1 and 120 characters.",
IDS_GEN_ENTERNEWPWD:"Please enter new password.",
IDS_GEN_ENTERCONFIRMPWD:"Confirm password cannot be blank.",
1915:"New password and confirm password do not match.",
IDS_MYPREFERNCES_PASSWORD_ERROR_MSG:"Please enter your current password to edit your Pearson account",
IDS_MYPREFERNCES_EDIT_P_ACCOUNT:"Edit Pearson account",
IDS_MYPREFERNCES_MIN_SIX_CURRENT_USERNAME:"Current Username",
IDS_MYPREFERNCES_CURRENT_PASSWORD:"Current Password",
IDS_MYPREFERNCES_ENTER_USERNAME:"Please enter a username.",
IDS_MYPREFERNCES_ENTER_PASSWORD:"Please enter a Password.",
IDS_MYPREFERNCES_PASSWORD:"Password",
IDS_MYPREFERNCES_USERNAME:"Username",
IDS_MYPREFERNCES_EDIT_OR_CANCEL:"Edit your password in the fields provided below and click Save. To keep your current password, click Cancel.",
IDS_MYPREFERNCES_PASSWORD_MISMATCH:"The passwords do not match.",
IDS_MYPREFERNCES_CHANGE_UP_INFO:"Enter your current password in the field provided below and click Continue.",
IDS_MYPREFERENCES_ENTERRETYPEPWD:"Re-type password cannot be blank.",
IDS_GEN_ASSIGNNEXTCLASS:"Assign and Go to Next Class",
IDS_MYPREFERNCES_WRONG_USERNAME_PASSWORD:"The username or password you entered is incorrect. Please enter the correct username and password to update your profile.",
IDS_ASSESSMENT_TOOL_ENTER_VALID_SCORE_ALERT:"Enter valid score",
IDS_165_All:"All",
IDS_Subscription_Failed_Subscription:"We are unable to process your subscription. Would you like to subscribe again?",
IDS_ENROLLMENT_LPLC0014:"Active License pool(s) for the given organization and product not found",
IDS_ENROLLMENT_LPLC0011:"The license pool has expired",
IDS_Sub_Reason:"Reason:&nbsp;",
IDS_GEN_FrameworkCode:"Code",
MSG_ID_SHOWENROLLMENT:"Show Enrollments",
BUSINESS_UNIT_EMPTY_ERROR_MESSAGE:"Please enter a Business Unit value.",
BUSINESS_UNIT_DUPLICATE_MESSAGE:"A Business Unit with this name already exists.  Please correct the Business Unit value to make it unique.",
BUSINESS_UNIT_LENGTH_VALIDATION_MESSAGE:"Length of Business Unit name can not exceed 50 characters.",
LTI_Header:"Import LTI Activity Links",
LTI_Header_Wait:"Upload Status",
LTI_Header_OnComplete:"Import Complete",
LTI_Header_OnFailed:"Import Failed",
LTI_SuccessMsg:"The import completed successfully. # links were created.",
LTI_FailureMsg_Header:"The import failed. No links were created.",
LTI_SuccededWithMissingSkillsMsg:"The cartridge you imported contains skills that are not added to this course. Please verify the course preferences to ensure that the correct skill frameworks are added to the course.",
LTI_CartridgeWithNoSkillsMsg:"The activities in the file you imported are not aligned to any skills.",
LTI_InvalidCatridge:"The file you tried to import was not a valid cartridge. Please check the file and try again.",
GEN_PREFERENCE_CUSTOMSUPPORTLINK:"Enter Custom Support Link",
GEN_VERIFY_LINK:"Check Link",
9997:"Please enter a valid Custom Support Link",
9996:"The Number of Character Should between 1 to 255 before @",
9998:"Enter valid Custom Support Link",
IDS_Show_selected_State:"Show in Selected States",
IDS_Selected_State:"Selected States",
IDS_Show_In:"Show in&nbsp;",
IDS_PREF_LL_DUPLICATE_SCORMCODE:"Multiple Learner Levels cannot share the same SCORM code",
IDS_PREF_LL_VALIDATE_SCORMCODE:"Only alphanumeric characters may be used",
IDS_PREF_LL_VALIDATE_LANGUAGES:"Please select at least one Learner Language.",
LTI_SOME_ERROR_OCCURRED_MESSAGE:"Some error occurred while processing your request, please try again.",
LTI_CHANGES_SAVED_SUCCESSFULLY_MESSAGE:"Changes saved successfully.",
LTI_MORE_THAN_500_CHARACTERS_MESSAGE:"Editor can not contain more than 500 characters.",
IDS_SETTINGS_STUDYPLAN_THRESHOLD_MESG:"Learning objective/skill threshold score to pass updated successfully.",
IDS_PREF_LTIACTIVITY_NOOFATTEMPTS:"(If blank, unlimited attempts are allowed.)",
IDS_PREF_LTIACTIVITY_DEFAULTSUCCESSMSG:"Default Preferences updated successfully",
IDS_PREF_LTIACTIVITY_REFERENCEMSG:"An LTI activity type is used in this course. Before you can remove the tool from the course, you must first delete the related activities.",
IDS_PREF_GRADING_VALID_PARTIAL_CREDITVALUE:"Enter a valid partial credit value (whole numbers from 0 to 100).",
IDS_PREF_WC_INSTMAXMSG:"Maximum 8 instructional areas can be added ",
IDS_PREF_WC_INSTTITLEEMPTY:"Instruction Title cannot be empty",
IDS_PREF_WC_INSTRUCTIONTITLEEMPTY:"Please enter a Title for instruction",
IDS_PREF_WC_INSTINVALIDCOLOR:"Instruction Hex Color value is invalid. ",
IDS_PREF_WC_FBSUCCESSADD:"Feedback Schema added successfully.",
IDS_PREF_WC_FBTEXTSUCCESSMSG:"Feedback Text added successfully.",
IDS_PREF_WC_FBCREATEMSG:"Feedback Schema created successfully.",
IDS_PREF_WC_FBUPDATEMSG:"Feedback Schema updated successfully.",
IDS_PREF_WC_INSTCREATEMSG:"Instructions created successfully.",
IDS_PREF_WC_INSTUPDATEMSG:"Instructions updated successfully.",
IDS_PREF_WC_INSDELETEDMSG:"Instructions deleted successfully.",
10006:"Score saved successfully.",
LTI_SOME_ERROR_OCCURRED_MESSAGE:"Some error occurred while processing your request, please try again.",
6069:"Score must be less than the maximum score of the question.",
Ids_Do_u_wantsave:"You have not saved your changes. Do you want to save before continuing?",
IDS_WC_ADDSCHEMA_EDITFEEDBACK:"Edit Feedback",
IDS_CUST_CANNOTBE_BLANK:"cannot be blank",
IDS_CUST_VALUE_INVALID:"value is invalid",
IDS_CUST_DEFAULT_FONTCOLOR:"Default font color for",
IDS_CUST_IS_APPLIED:"is applied",
IDS_COURSEBANNERBG:"Course Banner background Color",
MSG_ID_5182:"Preferences updated successfully.",
IDS_ERR_GRACE_SETTING_EMPTY:"All fields for the Grace Period settings are required.",
IDS_ERR_MAXIMUM_DEDUCTION_VALUE:"Maximum Deduction cannot be zero and must be greater than the Amount To Deduct.",
IDS_PREF_GRACEPERIOD_AMOUNTTODEDUCT_MAXDEDUCTION:"Amount to deduct must be less than or equal to Maximum deduction.",
IDS_PREF_GRACEPERIOD_AMOUNTTODEDUCT_RANGE:"The Amount to deduct has to be in range 0 – 100.",
IDS_CS_ERR_MAX_DEDUCTION:"The Maximum deduction value must be less than or equal to 100.",
IDS_COURSESETTING_COURSEBRANDING_LOGO_IMAGE:"The file you selected for the Course Banner image is not a supported image type. Please try again.",
7802:"Threshold score must be between 1 and 100.",
3527:"Value should be greater than 0.",
IDS_DEFINE_BGCOLOR:"You must define a background color for each course banner.",
IDS_CATALOG_ADDICON:" + Add another Icon",
IDS_CTB_TAGID_2:"Display as tab on main navigation row",
IDS_CTB_TAGID_0:"Display under Content tab",
IDS_CTB_TAGID_4:"Display under Enrollment tab",
IDS_CTB_TAGID_47:"Move under Gradebook tab",
IDS_CTB_ENABLE:"Enable",
IDS_CTB_DEFAULTVIEW:"Default View",
IDS_CTB_TOOLBARORDER:"Toolbar Order",
IDS_SAB_CORRECTANSWERS:"Correct Answer",
IDS_OC_MSGADDCONTENT:"To add course materials to your course, click the Add Course Materials button.",
IDS_OC_MSGADDCORCEMATRL:"To add course materials to your course, click the Add Course Materials button.",
Allow_Resubmission_Essay:"Allow student to resubmit essay questions is set successfully",
Maxscore_Userscore_Alert:"Max score must be greater than user score.",
Raw_Maxscore_Alert:"Max score must be greater than 0.",
IDS_PREF_TOOLSVALIDATIONMSG:"Please upload the supported formats like JPG, GIF, PNG.",
IDS_PREF_SKILLSTDS_TEXTVALIDATION:"Label may contain up to 20 characters only. Please enter a shorter name.",
IDS_PREF_EDIT_MGMQUESTION:"Questions have been updated successfully.",
CAT_Settings_txtauthorFirstname:"First",
CAT_Settings_txtauthorMI:"Middle initial",
CAT_Settings_txtauthorLastname:"Last",
IDS_GEN_GBDelete:"Delete",
DEFAULT_PREF_MASTERY_ERR:"You must define the mastery threshold when you include in mastery reports",
IDS_FEEDBACK_ASSETTYPENAME_25:"Module",
INVALID_ZIP_MATHXLCARTRIDGE:"The file you tried to import was not valid. Please check the file and try again.",
CARTRIDGE_PROCESSOR_EXCEPTION:"The file you tried to import was not valid. Please check the file and try again.",
RESOURCE_FILE_MALFORMED:"The file you tried to import was not valid. Please check the file and try again.",
FILE_NOT_FOUND:"The file you tried to import was not valid. Please check the file and try again.",
VALIDATION_AGAINST_TOOL_FAILED:"The file you tried to import failed. Please try by selecting different tool.",
CARTRIDGE_TO_DTO_FAILED:"The file you tried to import was not valid. Please check the file and try again.",
INVALID_RESOURCE_HANLDER:"The file you tried to import was not valid. Please check the file and try again.",
ASSIGNMENT_LINK_ASSOCITION_FAILED:"The file you tried to import was not valid. Please check the file and try again.",
IDS_GLOSSARY_UploadStatus:"Glossary upload in progress",
IDS_GLOSSARY_UploadStatus1:"Glossary upload complete",
IDS_ZipCode_Empty:"ZIP Code required.",
IDS_ASS_MULTIPLE_RESPONSE_OPTION:"option",
IDS_CATALOG_SYNICON_IMGFORMATMSG:"The file you selected for the course icon is not a supported image type. Please try again.",
IDS_CATALOG_SYNICON_ADDICONMSG:"You must choose an image for this icon before you can add another icon.",
IDS_TOC_CONFMSG:"If any of the items you selected are marked as Instructor Only, they cannot be assigned to students. Do you want to            continue and assign only those selected items which are not Instructor Only?",
IDS_TOC_CONF_CHECKSELCT:"This item is currently assigned. Marking it Instructor Only will unassign the item. Do you want to continue?",
IDS_PREFTOOL_CREATE_SUCCESS:"Module Tools created successfully.",
IDS_GEN_PASSWORDNOTMATCHING:"Passwords do not match. Please re-enter.",
IDS_GEN_VALIDATECURRENTPWD:"New password cannot be current password.",
IDS_PRODUCT_PRODUCTBRANDING_LOGO_IMAGE:"Image type is incorrect. Review specifications and upload a new image.",
IDS_ASSESSMENTTOOL_FRMADAPTIVEASSESSMENT_Schedule:"Schedule",
LessonPlan_Assign:"Assign",
IDS_GB_MOVECOLUMN_MESSAGE:"Column moved successfully.",
IDS_GEN_CLIPBOARDITEMS:"Clipboard Items",
1512:"Some special characters are not allowed.",
ID_STUMGMT_FILTERMSG:"Please select at least one item.",
9004:"Properties updated successfully.",
IDS_NOACTIVECLASSES:"You currently have no active classes.",
IDS_GEN_CSVFILE:"csv file",
IDS_GEN_TABDELIMITEDFILE:"tab delimited file",
IDS_GEN_PDFFILE:"pdf file",
IDS_VS_COMMENTS_SAVED_MESSAGE:"Comments saved successfully.",
IDS_DELETE_COMMENTS:"Comment removed successfully.",
IDS_Announcement_Delete:"This announcement has been deleted.",
ID_CAL_BACKTOMONTH:"Back to Month",
ID_CAL_ADVCAL:"View Advanced Calendar",
ID_CAL_ACM:"Assign Course Materials",
ID_CAL_HEDSETUP:"Setup",
IDS_ShownToStudents:"Shown to Students",
IDS_ShownToSelectedStudents:"Shown to Selected Students",
IDS_HiddenFromStudents:"Hidden from Students",
IDS_AssignedDue:"Assigned: Due ",
IDS_Assigned:"Assigned",
IDS_NotAssigned:"Not Assigned",
IDS_AvailableTo:" to ",
IDS_GEN_Someactivitysaddalready:"Some activities are already added.",
IDS_PREFERENCE_1628_ERRORTEXT:"Please select an eText",
10078:"Number of attempts must be between 1 and 9999.",
LEGEND_12:"Past Due",
IDS_ImDone:"I\'m Done",
IDS_1546_Start:"Start",
IDS_1546_View_Submissions:"View Submissions",
IDS_1546_Try_Again:"Try Again",
IDS_1546_Continue:"Continue",
ID_TOD_NOTGRADED:"Not Graded",
TODO_ERROR_DONELIST:"You have no items on your Completed list",
TODO_ERROR_TODOLIST:"You have no items on your To Do list",
TODO_ERROR_INPROLIST:"You have no items currently In Progress",
TODO_ERROR_PASTDUELIST:"You have no past due items",
9034:"You cannot open this module yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
9035:"You cannot open this activity yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
9036:"You cannot open this page yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
9037:"You cannot open this link yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
9039:"You cannot open this file yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
Msg9555:"The study plan is no longer available because it is past the due date.",
TOPIC_UNAVAILABLE:"You cannot open this discussion yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
9042:"You cannot open this practice lesson yet. Either your instructor has made it unavailable to you, or your instructor has scheduled it to be available to you on another day.",
STUDYPLAN_UNAVAILABLE:"Your teacher has not scheduled this Study plan for you, or the Study plan is not scheduled for the current date.",
IDS_CC_PREF_CUSTOMUI_TITLEVALIDATION:"Custom UI View title field cannot be blank.",
IDS_CUSTOMUI_ERROR_FILENOTSELECTED:"Please select a file to upload.",
IDS_CUSTOMUI_ERROR_ZIPFILEFORMAT:"The file you chose is in the wrong format. Please choose a .zip file to upload.",
IDS_CUSTOMUI_ERROR_SAVEPREFERENCES:"When Enable custom Flash view is enabled, you must choose a valid .zip file and click Upload before Saving preferences.",
ID_CU_CUSTOMUI:"CUSTOM",
IDS_GEN_CHOpen:"Open",
IDS_DRT_OPENMODULE:"Open Study Plan",
IDS_Content_ContentLibrary:"Course Materials Library",
IDS_GEN_QLibrary_Export_Msg:"The export for &nbsp;",
IDS_GEN_QLibrary_Export_Msg1:"&nbsp; is being processed. When finished, the file will be placed in the ",
IDS_GEN_QLibrary_Export_Msg2:". You can then download the file to your desktop ",
IDS_GEN_QLibrary_Export_Msg3:"The Print for &nbsp;",
ID_SELECT_ONE_FILE:"You must select at least one file to upload.",
IDS_PRODUCTS_YES_SUBSCRIBE_Failed:"Subscription Failed!",
KF_DLTCONFIRM_MSG:"Are you sure you want to delete the selected Key Feature? This action cannot be undone.",
KF_DLTD_SUCCESSMSG:"Selected Key Features deleted successfully.",
IDS_CC_PREF_KF_UPDATEMSG:"Key Feature updated successfully.",
IDS_CC_PREF_KF_SUCCESSMSG:"Key Feature added successfully.",
IDS_CC_PREF_EBOOKCODE_VALIDATION:"EBook Code cannot be blank.",
IDS_VIEWED_LATE:"Viewed Late",
IDS_AM_STARTED:"Started",
ID_EBOOKPLUS_UPDATED:"eText updated successfully",
IDS_GEN_OPEN:"Open",
IDS_DISCUSSION_POSTRESPONSE:"Post Response",
IDS_MaximizeCourse_AltText:"Maximize My courses and Testbanks",
IDS_MinimizeCourse_AltText:"Minimize My courses and Testbanks",
IDS_MinimizeAnnouncement_AltText:"Minimize Announcements",
IDS_MaximizeAnnouncement_AltText:"Maximize Announcements",
IDS_MinimizeCalendar_AltText:"Minimize Calendar",
IDS_MaximizeCalendar_AltText:"Maximize Calendar",
IDS_BOOK_CODE_NOT_BLANK:"Book Code can not be blank.",
IDS_CLASS_CREATED_SUCCESSFULLY:"Class added successfully.  To rearrange additional classes in your list, click on the arrow next to the class title and select ‘Move Up’ or ‘Move Down’.",
IDS_GRADES_UPDATE_INPROGRESS:"Any applicable grades for the updated due date are being processed. Please check after a few minutes.",
IDS_GEN_SM_MARK_COMPLETE_CONFIRMATION:"You have successfully marked this item complete.",
IDS_GEN_SM_UNDO_MARK_COMPLETE_CONFIRMATION:"You have successfully revoked the complete status for this item.",
IDS_GEN_SM_REASSIGN_CONFIRMATION:"You have successfully reassigned this item.",
IDS_GEN_SM_REASSIGNSM_CONFIRMATION:"You have successfully reassigned this item and study materials.",
IDS_GEN_SM_COURSE_COMPLETE_CONFIRMATION:"You have successfully marked this course complete.",
IDS_GEN_SM_COURSE_INCOMPLETE_CONFIRMATION:"You have successfully marked this course incomplete.",
IDS_HED_DueDateEndDate_Alert:"Due Date and Time must be on or before End Date and Time",
IDS_FILENAME_MAC:"Special characters like : or / are not allowed in filename",
IDS_PASTDUE_ACCEPT_BEFORE_GRADE:"You must accept the past due submission in order to grade the activity.",
IDS_165_TOC:"TOC",
IDS_CC_ADD_CONTENT:"Add from Library",
IDS_GEN_MAPSKILLS:"Map Skills",
IDS_CC_ORGANIZECONTENT:"Manage Course Materials",
IDS_GEN_LAUNCH:"Launch",
IDS_QUESTIONFOLDER_DOWNLOAD_AS_WORLD_CONFIRMATION_1:"The Word file ",
IDS_QUESTIONFOLDER_DOWNLOAD_AS_WORLD_CONFIRMATION_2:" is being processed. When finished, click on the Downloads button to download the file to your desktop.",
IDS_Restrict_Access_Save_Msg:"Restrict Access password saved successfully.",
IDS_Restrict_Access_Clear_Msg:"Restrict Access password cleared successfully.",
IDS_Badging_SelectedAssets:"Multiple Selected",
IDS_Badging_Validate_Mandatory:"You must enter mandatory fields",
IDS_Badging_Validate_ValidThreshold:"Please enter a valid badging threshold to save with badging enabled. The threshold should be between 1 and 100%",
IDS_Badging_Templates:"To save badge preference at least one badge template should be available",
IDS_Badging_NoRecordMessage:"No records exist",
IDS_WC_SELECTED:"Selected",
IDS_WC_NOTSELECTED:"Not selected",
IDS_WC_EXPAND:"Expand",
IDS_WC_COLLAPSE:"Collapse",
IDS_WC_GRAMMATICALERROR:"Grammatical Error:",
IDS_WC_DISABLED:"Disabled",
IDS_WC_VAGUEADJECTIVEERROR:"Vague adjective error",
IDS_WC_REPEATEDWORDERROR:"Repeated word error",
IDS_WC_PRONOUNSANTECEDENTERROR:"Pronouns/Antecedent error",
IDS_WC_SPELLINGERROR:"Spelling error",
IDS_WC_REPEATEDIDEAERROR:"Repeated Idea error",
IDS_Badging_Validate_Mandatory:"You must enter mandatory fields",
IDS_SMSI_ENTERCOURSE1:"Please enter the course ID.",
IDS_GEN_CourseID_Not_Null:"Please enter the valid Course ID ",
SynapseAdmin_RegisterUser_FirstNameLastName:"You must enter a first name and last name. They cannot be blank.",
IDS_ProgramAdmin_EmailErrMsg:"Please enter email address.",
IDS_GEN_GBSUM:"Sum",
IDS_GEN_GBAVG:"Avg",
IDS_ASSIGN_WindowName:"assign",
IDS_USERTRANSFER_UPLOAD_CONFIRMATION:"Your transfer request has been successfully submitted. It may take a few minutes for the users to appear in their new school.",
IDS_WEB_DRTUX_PRETEST_LASTATTEMPT:"This is the last time you can attempt this activity. You may be able to save it if you have \"Save for Later\" allowed. After you complete the activity, your score is recorded and sent to your instructor.",
IDS_LS_SavingMessage:"Saving...",
IDS_LS_FailedMessage:"Saving Failed.Please try again",
IDS_PageNavigation_Message:"Are you sure you want to leave this page?",
IDS_GBR_Validate_DateRange_FromDate:"From date and To date Range Shound not be same :",
IDS_GBR_Validate_DateRange_ToDate:"From date and To date Range Shound not be same :",
IDS_GBR_Validate_DateRange_LMSCourse:"Enter neither LMS Course IDs nor Date Range:",
IDS_GBR_Validate_DateRange:"From date and To date Range Shound not be same :",
IDS_GBR_Validate_Message:"Enter LMS-CourseIDs or Date Range :",
7940:"From date must be less than the To date.",
IDS_GEN_ENTER_TODATE:"Please enter To date.",
IDS_GEN_ENTER_FROMDATE:"Please enter From date.",
IDS_PGR_StatusMessage:"Processed Lms-CourseIds Status = ",
IDS_PGR_MismatchExists:"Mismatch Exists",
IDS_PGR_NoMismatch:"No Mismatch",
IDS_PGR_BadRequest:"Bad Request",
IDS_PGR_CourseNotFound:"Course Not Found",
IDS_PGR_RequestTimeout:"Request Timeout",
IDS_PGR_FailedFatal:"Failed Fatal",
IDS_COURSESETTINGS_DEFAULTPREFE_RECORDTIME_ALERT:"Invalid Recording Time.",
IDS_PREF_MINIMUM_MAXIMUMNUMPARTICIPANTS_ERRORMSG:"Minimum or maximum number of participants field cannot be empty.",
IDS_MINUTESECONDS_ERRORMESSAGE:"Maximum length of recording minutes or seconds field cannot be empty.",
IDS_PREF_MINIMUM_PARTICIPANTS_ERRORMSG:"Minimum number of participants cannot be grater than maximum number of participants.",
IDS_PREF_MINIMUM_PARTICIPANTS_VALUE:"Minimum number of participants value should be between 2 to 6.",
IDS_PREF_MAXIIMUM_PARTICIPANTS_VALUE:"Maximum number of participants value should be between 2 to 6.",
IDS_MINIMUM_MINUTESECONDS_ERRORMESSAGE:"Minimum length of recording minutes or seconds field cannot be empty.",
IDS_PREF_LENGTH_OF_RECORDING_ERRORMSG:"Minimum length of recording cannot be grater than Maximum length of recording.",
IDS_PREF_RECORDING_VALUE:"Recording value should be between 1 to 15.",
Assessment_AVChat_Stop_Recording_message:"Please stop recording and submit the assignment.",
IDS_MANAGEGRADING_VALIDATION_MSG:"Manage gradebook rounding value should be integer digits between 0 to 4 ",
ASSESSMENT_AVCHAT_VS_GD_ALERTMSG:"Please insert score in the text box next to ‘Apply grade to all students’ button. Score must be greater than 0 or less than or equal to max score",
IDS_Property_VideocahtGroups:"Video Chat Groups",
IDS_Property_VideoGroupsLabel:"Choose which video chat groups will receive this assignment",
IDS_AUTO_EmptyErrMsg:"You must first select a file before attempting to upload.",
IDS_AUTO_WrongErrMsg2016:"You have uploaded the wrong file. Please try uploading again, ensuring that you have selected a Microsoft Office file.",
IDS_AUTO_WrongErrMsg:"You have uploaded the wrong file. Please try uploading again, ensuring that you have selected a Microsoft Office 2007/2010/2013 file with a file name matching what is specified in the Instructions.",
IDS_AUTO_TEMPFILE:"myitlab:grader cannot process temp files. Please return and upload a valid file instead.",
ID_PopUpBlockerWarningMsg:" We have detected your popup blocker being active.This Pearson MyLab requires the popup blocker to be disabled for an optimum experience.Please visit ",
ID_PopUpBlockerTextLink:"link",
ID_PopUpBlockerTextHelp:" for help.",
ID_PopUpBlockerWarningURL:"https://support.pearson.com/getsupport/s/article/Pop-Up-Blockers/",
IDS_AUTO_Download:"Download Starting Materials",
IDS_GRADERIT_STEP2_TEXT:"Work Assignment on your Computer",
IDS_GRADERIT_STEP3_TEXT:"Upload Completed Assignment",
IDS_GRADERIT_STEP4_TEXT:"Submit Assignment for Grading",
IDS_GRADERIT_STEP1_DESCRIPTION:"You must download the starting files available below. The file for this assignment will be unique to you, so make sure to save it where you know you can retrieve it easily.",
IDS_GRADERIT_STEP2_DESCRIPTION:"Follow the instructional steps to finish the project (point values can also be seen using the link below).",
IDS_GRADERIT_STEP3_DESCRIPTION:"All done? Now upload the project file in preparation for our automatic grading and reporting process.",
IDS_GRADERIT_STEP4_DESCRIPTION:"Detailed feedback and grades on the submitted project are added to your submission and will be made available via the MyITLab gradebook and submission report screen.",
IDS_GRADERIT_BUTTONTEXT_DOWNLOADMATERIAL:"Download Materials",
IDS_GRADERIT_BUTTONTEXT_PREVIEW:"Preview Steps",
IDS_GRADERIT_BUTTONTEXT_CHOOSEFILE:"Choose File..",
IDS_GRADERIT_SubmitforGrades:"Submit for Grading",
IDS_GRADERIT_BUTTONTEXT_UPLOAD:"Upload",
IDS_GRADERIT_STEP1:"1",
IDS_GRADERIT_STEP2:"2",
IDS_GRADERIT_STEP3:"3",
IDS_GRADERIT_STEP4:"4",
IDS_GRADERIT_FILE_SELECTED_MESSAGE:"No File Selected.",
IDS_GRADERIT_FILE_SELECTED:"Selected file:",
IDS_GRADERIT_CANCEL:"Cancel",
IDS_GRADERIT_UNDO:"Undo",
IDS_AUTO_Download:"Download Starting Materials",
IDS_GRADERIT_DOWNLOAD_ALL_FILES:"Download All Files",
IDS_GRADERIT_ASSIGNMENT_INSTRUCTION:"Assignment Instructions",
IDS_GEN_CLOSE:"Close",
IDS_GRADERIT_ASSIGNMENT_CONTINUE:"You can close this assignment and continue.",
IDS_GRADERIT_ASSIGNMENT_CLOSE:"Close Assignment",
IDS_GRADERIT_SUBMITTING_ASSIGNMENT_AGAIN:"Please try submitting your assignment again.",
IDS_GRADERIT_SUBMITTING_ASSIGNMENT_GRADING:"Submitting your assignment for grading...",
IDS_GRADERIT_SUBMITTING_ASSIGNMENT_MESSAGE:"<strong>Kudos!</strong> Your file has been submitted for grading.",
IDS_GRADERIT_SUBMITTING_ASSIGNMENT_ERROR:"<strong>Server Error:</strong> Your file was not submitted for grading.",
IDS_SERVER_DOWN:"Server is Currently unavailable, please try after some time",
IDS_GRADERIT_LITERAL_UPLOADING:"Uploading:",
IDS_AUTO_FileSizeLimit:"myitlab:grader cannot process files larger than 5MB. Please return and upload a smaller file instead.",
JS_LOCALIZATION_EMPTY_RESOURCE_KEY:"Key not added to the list in the sub JSLocalizedResourceKeys.InitializeResourceKeys()"
}
function getLocalizedString(resourceKey)
{
 if(objResources[resourceKey] != undefined)
     return objResources[resourceKey];
 else
     return objResources['JS_LOCALIZATION_EMPTY_RESOURCE_KEY'];
}
var objJsDate = {
dayNames:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
monthNames:['January','February','March','April','May','June','July','August','September','October','November','December',''],
abbrDayNames:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
abbrMonthNames:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec',''],
strLocalizedFirstDayofWeek:0

}